### ISSUE TITLE
Stupid question- How can I actually use this code???

### ISSUE THREAD

**Issue by daddyDa** [halsafar/Vega64SoftPowerTableEditor#5]
Hey guys, 
I'm brand new to this, how can I get this program running on windows? I do not see any .exe download, the package i download how could i compile it? thanks

**Comment by halsafar** [comment]
Hey daddyDa.  On GitHub if you check out the front page for a repository there is sometimes a "Releases" link you can click.

A zip of this project compiled is there, https://github.com/halsafar/Vega64SoftPowerTableEditor/releases

That should get you started.
